include:
  - infrastructure.repos.epel
  - dnsmasq
  - resolver
  - ntp
  - fail2ban
  - fail2ban.config
  - logrotate
  - logrotate.jobs
  - sssd
  - pam
  - nsswitch
  - infrastructure.common_admin_tools
  - infrastructure.ssh_keys
